services:
  backend:
    build:
      context: ./backend
      args:
        GTFS_RT_URL: https://proxy.transport.data.gouv.fr/resource/sncf-all-gtfs-rt-trip-updates
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data 

  frontend:
    build:
      context: ./gtfs-dashboarding
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8000
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
