services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data 

  frontend:
    build:
      context: ./gtfs-dashboarding
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8000
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
